backbone_layers:
- 2
- 3
- 7
batchsize: 32
betas:
- 0.9
- 0.999
bos_token: 1
channels: 1
config: pix2tex/model/settings/multiline_training.yaml
data: dataset/multiline/train_resized.pkl
debug: false
decoder_args:
  attn_on_attn: true
  cross_attend: true
  ff_glu: true
  rel_pos_bias: false
  use_scalenorm: false
device: mps:0
dim: 256
encoder_depth: 4
encoder_structure: hybrid
eos_token: 2
epoch: 0
epochs: 10
gamma: 0.9995
gpu_devices: []
heads: 8
id: nxs3hcnn
load_chkpt: pix2tex/model/checkpoints/weights.pth
lr: 0.001
lr_step: 30
max_dimensions:
- 672
- 192
max_height: 192
max_seq_len: 512
max_width: 672
micro_batchsize: 8
min_dimensions:
- 32
- 32
min_height: 32
min_width: 32
model_path: multiline_checkpoints
name: local_multiline_pix2text-resized-0324
no_cuda: false
num_layers: 4
num_tokens: 8000
optimizer: Adam
output_path: multiline_outputs
pad: true
pad_token: 0
patch_size: 16
resume: false
sample_freq: 300
save_freq: 1
scheduler: StepLR
seed: 42
temperature: 0.2
test_samples: 5
testbatchsize: 20
tokenizer: dataset/tokenizer.json
valbatches: 100
valdata: dataset/multiline/val_resized.pkl
wandb: true
